### ISSUE TITLE
sd卡读写问题

### ISSUE THREAD

**Issue by weypro** [FASTSHIFT/Arduino-For-Keil#17]
用stm32f103c8t6核心板。sd卡库编译通过，但是连不上sd卡。用stm32的spi引脚（PA4 CS, 5 SCK, 6 MISO, 7 MOSI）。我用stlink调试得到卡在了SdVolume的init初始化上，前一步card.init可以。想得到大佬的帮助。

**Comment by FASTSHIFT** [comment]
@weypro 
加我Q：1290176185，我把调好的SdFat给你

**Comment by FASTSHIFT** [comment]
@weypro 
用stm32duino的框架可以读写SD吗？

**Comment by weypro** [comment]
来结个题，感谢大佬帮助。可以通过换杜邦线和降低spi速度来解决。此外，若用stlink调试出现card.init成功，但在volume.init这一步失败的情况，不调试直接运行即可。
